# Generated by Django 2.0.6 on 2018-06-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pedido', models.TextField()),
                ('asunto', models.TextField()),
                ('detalles', models.TextField()),
                ('prioridad', models.TextField()),
                ('sistema', models.TextField()),
                ('fecha', models.DateTimeField(verbose_name='Fecha Publicada')),
                ('archivo_adjunto', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Usuario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tecnico_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Tecnico'),
        ),
    ]
